config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'translation#index'
  post '/translate', to: 'translation#create'
  post '/past_search', to: 'translation#past_search', :as => :past_search_path
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/translation.rb
class Translation < ApplicationRecord
    #Make sure for Translation object to have attributtes if created.
    validates_presence_of :english
    validates_presence_of :gorbyoyo

    #Main Translate function calls other function to take string and fully translate, also check for if string.
    #needs to be verified if string is "i am not selling knives" or is prepared to that.
    def self.translate(input_string)
        #Main logic changes string to Gorbyoyo.
        english = Translation.prepare_string(input_string)
        dorbdorb = Translation.translate_to_dorbdorb(english)
        gorbyoyo = Translation.translate_to_gorbyoyo(dorbdorb)

        #Check to see if prepared string turned into "i am not selling knives" if it is it can be verified by the API.
        if (english == "i am not selling knives")
            if (Translation.verify_translation(gorbyoyo) == "Success")
                return [english, gorbyoyo]
            else    
                return "Error in translation"
            end
        else
            return [english, gorbyoyo]
        end

    end

    #Uses endpoint to verify phrase "i am not selling knives".
    def self.verify_translation(gorbyoyo_translation)
        #Sends apps translation of gorbyoyo and sends it to endpoint and gets a response string.
        response = HTTParty.post("https://72exx40653.execute-api.us-east-1.amazonaws.com/prod/confirmtranslation",
              :body => {:textToVerify => gorbyoyo_translation}.to_json,
              :headers => {'Content-Type' => 'application/json'}
        ).to_s

    end

    #Function turns DorbDorb into Gorbyoyo, it expects an array of strings and uses guide to transform them into Gorbyoyo.
    def self.translate_to_gorbyoyo(dorbdorb_response)
        #Creates string by joining an array where each string in the Dorbdorb array is broken into parts an int1, char, int2.
        #Those parts are reconstructed into char + yo + (int1 + int2).
        gorbyoyo_translation = dorbdorb_response.map do |dorbdorb_string|
            dorbdorb_array = dorbdorb_string.scan(/\d+|\D+/)
            gorbyoyo = "#{dorbdorb_array[1]}yo#{dorbdorb_array[0].to_i + dorbdorb_array[2].to_i}"
        end.join("")

    end

    #Function turns prepared english string into Dorbdorb by calling endpoint with array as return.
    def self.translate_to_dorbdorb(english_string)
        #Json response is an array with each character in string converted into Dorbdorb.
        HTTParty.post("https://72exx40653.execute-api.us-east-1.amazonaws.com/prod/translateEnglishToAlien",
              :body => {:textToTranslate => english_string}.to_json,
              :headers => {'Content-Type' => 'application/json'}
        ).parsed_response

    end

    #Function uses gsub to remove punctuation and digits from string. Returns string without those characters.
    def self.prepare_string(input_string)

        input_string.downcase.gsub(/[^a-z\s]/i, '')

    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/translation_controller.rb
class TranslationController < ApplicationController

    def index
        #Main route check for existince of previous translation route redirect
        #if so display vaariable becomes past translation chosen
        #else display last translation created

        @translations = Translation.all
        if params[:past_translation]
            @previous_translation = @translations.find(params[:past_translation])
        else
            @previous_translation = @translations.last
        end
    end

    def create
        #Check input to make sure it meets standard. If not no create (could not get sweetify to work on Rails)
        #Sends back to index route

        if (params[:translation][:english].length > 0 && params[:translation][:english].length < 70)
            translation_array = Translation.translate(params[:translation][:english])
            translation_params = {english: translation_array[0], gorbyoyo: translation_array[1]}
            
            Translation.create(translation_params)
        end

        redirect_to action: "index"
    end

    def past_search
        #Route sends chosen past translation to index route to be displayed through params

        found_translation = Translation.all.find(params[:id])

        redirect_to action: "index", past_translation: found_translation
    end

    #Strong params used to make sure correct information is given through params and creation
    private

        def translation_params
            params.require(:translation).permit(:english, :gorbyoyo)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translate_helper.rb
module TranslateHelper
end

app/helpers/translation_helper.rb
module TranslationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Translator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'nav', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= render 'sweetify/alert' %>
  </body>
</html>

app/views/translation/index.html.erb
<%# Div container holds display elements, the title and translation output. %>
<div class="display-container">
    <h1 class="title">Alien Translator</h1>
    <div class="display">
        <% if @previous_translation == nil %>
            <h2>No previous translation</h2>
        <% else %>
            <h2>Gorbyoyo</h2>
            <h3 class="display-text"><%= @previous_translation.gorbyoyo %></h3>
            <h2>English</h2>
            <h3 class="display-text"><%= @previous_translation.english %></h3>
        <% end %>
    </div>
</div>

<%# Form to submit english phrase to controller. Form sends string and authenticity token %>
<div class="input">
    <form class="input-form" class="translate-phrase" action="/translate" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <p>Input a phrase here to translate to Gorbyoyo.</p>
        <div></div>
        <input type="text" name="translation[english]" id="english-input">
        <div></div>
        <input type="submit">
    </form>
</div>

<%# Side Navbar to include up to 10 past searches. If clicked display will show English and Gorbyoyo on display area. %>
<nav class="main-menu">
    <ul>
        <li>
            <i class="fa fa-bars fa-2x"></i>
            <span class="nav-text">
                Past Searches
            </span>
        </li>
        <% if @translations.length > 10 %>
            <% (1..10).each do |i| %>
                <li class="has-subnav">
                    <%= link_to past_search_path_url(:id => @translations[@translations.length - i].id), method: :post do%>
                        <i class="fa fa-microphone fa-2x"></i>
                        <span class="nav-text">
                            <%= @translations[@translations.length - i].english %>
                        </span>
                    <% end %>
                </li>
            <% end %>
        <% else %>
            <% (1..@translations.length).each do |i| %>
                <li class="has-subnav">
                    <%= link_to past_search_path_url(:id => @translations[@translations.length - i].id), method: :post do%>
                        <i class="fa fa-microphone fa-2x"></i>
                        <span class="nav-text">
                            <%= @translations[@translations.length - i].english %>
                        </span>
                    <% end %>
                </li>
            <% end %>
        <% end %>
    </ul>                
</nav>